Add logical selection to loc()
benjamingaudin/Frames pull request #24
Opened 2021-09-15 21:34 UTC by mreijnde

Add logical selection to loc() and move index selection code to Index class

Restructured subsasign to use these new selector function in Index class. What is your view on this?

todo: update testcases + add test cases

2021-09-16 18:42 UTC, mreijnde commented
I think the functionality now works, including the testcases. Could you have a look? 

- Index class has now all code to make index selection and validations
    -  getSelector() output a matlab compatible indexer (colon, logical array, or position index array) 
    -  positionOf() outputs always an position index array

- Assignments of dataframe selection code rearranged to split into
    - 1d indexing cases using Index.getSelector() method
    - 2d indexing (logical matrix) cases handled by modifyFromBool2D()
    
- Other DataFrame methods, eg dropIndex(), dropColumns() that use the selection will automatically support logical indexing

2021-09-19 22:02 UTC, benjamingaudin requested changes
Your code follows a good logic and I'll be happy to add your changes after you read my comments

2021-09-21 17:31 UTC, mreijnde commented on +frames/DataFrame.m
> +                         end
indeed, makes code clearer

2021-09-21 17:42 UTC, mreijnde commented on +frames/DataFrame.m
> +                "not matching number of cols in supplied data");
These lines, including lines 1183-1189 are a size check  between data and selector, with idea to get custom error message instead of failing on assignment. 1197-1201 is size between existing index.

Removed the initial size check, rely on just the internal matlab check.

2021-09-21 17:43 UTC, mreijnde commented on +frames/DataFrame.m
> +                 'Only single 2d logical selector allowed');
moved check to subsasgn

2021-09-21 17:44 UTC, mreijnde commented on +frames/Index.m
> +                "Position index out of range (%d)", length(obj));
removed them

2021-09-21 17:44 UTC, mreijnde commented on +frames/Index.m
> +                       "Only logical DataFrame-Series allowed for indexing");
k

2021-09-21 17:45 UTC, mreijnde commented on +frames/Index.m
> +                   "Logical index array should be vector (no matrix)");
k

2021-09-21 18:19 UTC, mreijnde commented
Thx for the detailed reviewing, the code improved. I have updated the pull request with the review comments, and added some additional testcases. Please let me know if something else has to change.

2021-09-22 20:06 UTC, merged

2021-09-22 20:07 UTC, benjamingaudin commented
Awesome work!